# Use root/example as user/password credentials

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-net

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false 
    networks:
      - backend-net

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - backend-net

  redisinsight:
    image: redislabs/redisinsight
    container_name: redisinsight
    ports:
      - 5540:5540
    volumes:
      - redis_insight:/db
    networks:
      - backend-net

volumes:
  mongo-data:
  redis-data:
  redis_insight:

networks:
  backend-net: