openapi: 3.0.0
info:
  title: Comment API
  version: 1.0.0
  description: API para gestionar comentarios

paths:
  /comment:
    get:
      summary: Obtener todos los comentarios
      tags:
        - Comment
      responses:
        '200':
          description: Lista de comentarios
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
    post:
      summary: Crear un nuevo comentario
      tags:
        - Comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewComment'
      responses:
        '201':
          description: Comentario creado exitosamente

  /comment/{id}:
    get:
      summary: Obtener un comentario por ID
      tags:
        - Comment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Un comentario
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'

    delete:
      summary: Eliminar un comentario por ID
      tags:
        - Comment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Comentario eliminado exitosamente

components:
  schemas:
    Comment:
      type: object
      properties:
        mensaje:
          type: string
          maxLength: 200
          description: Contenido del comentario
        FechaDePublicacion:
          type: string
          format: date
          description: Fecha en la que se publicó el comentario
        posteo:
          type: object
          description: Información básica del post asociado
          properties:
            Descripcion:
              type: string
              description: Descripción del post
            FechaDeCreacion:
              type: string
              format: date
              description: Fecha de creación del post
        usuario:
          type: object
          description: Información del usuario que hizo el comentario
          properties:
            nickName:
              type: string
              description: Apodo del usuario
            email:
              type: string
              format: email
              description: Correo electrónico del usuario

    NewComment:
      type: object
      required:
        - mensaje
        - FechaDePublicacion
        - userId
        - postId
      properties:
        mensaje:
          type: string
          maxLength: 200
          description: Contenido del comentario
        FechaDePublicacion:
          type: string
          format: date
          description: Fecha en la que se publicó el comentario (hasta 6 meses atrás)
        userId:
          type: integer
          description: ID del usuario que comenta
        postId:
          type: integer
          description: ID del post comentado
